# Generated by Django 2.2.12 on 2021-10-12 15:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeohashArea',
            fields=[
                ('geohash', models.CharField(help_text='Geohash of the map area', max_length=16, primary_key=True, serialize=False)),
                ('status', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Aggregated status for given geohash', null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Aggregated data for given geohash', null=True)),
            ],
        ),
    ]
