# Generated by Django 2.2.12 on 2021-10-17 12:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('key', models.CharField(help_text='Metric key identifier', max_length=4, primary_key=True, serialize=False)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Metric metadata', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='geohasharea',
            name='summary',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Aggregated summary for each category', null=True),
        ),
        migrations.AlterField(
            model_name='geohasharea',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Aggregated data for given geohash area', null=True),
        ),
        migrations.AlterField(
            model_name='geohasharea',
            name='status',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Aggregated status', null=True),
        ),
    ]
