# Generated by Django 2.2.12 on 2021-11-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20211021_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geohasharea',
            name='metadata',
        ),
    ]
